# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings - 基本站点设置
locale                   : "en-US"  # 网站语言区域设置
title                    : "Welcome!"  # 网站标题
title_separator          : "-"  # 标题分隔符
name                     : &name "Welcome!"  # 网站名称（使用 YAML 锚点）
description              : &description "I am an research assistant at Westlake University"  # 网站描述
url                      : https://EvomniDroid.github.io # 网站基础URL和协议，例如 "https://mmistakes.github.io"
baseurl                  : "" # 网站子路径，例如 "/blog"
repository               : "EvomniDroid/EvomniDroid.github.io"  # GitHub仓库名称

# Site Author - 网站作者信息，控制侧边栏作者内容的显示
#               如果字段为空，图标和链接将不会显示，否则会显示
#               可以通过编辑 /_includes/author-profile.html 进行额外自定义
author:
  # Biographic information - 个人信息
  avatar           : "zh.jpg"  # 头像图片文件名
  name             : "Hao Zhang"  # 姓名
  pronouns         : # 代词，例如: "He/his"  
  bio              : "Research assistant at Westlake University"  # 个人简介
  location         : "Hangzhou, China"  # 所在地
  employer         : "Westlake University"  # 工作单位
  uri              : # 个人网站URL
  email            : "zhanghao15@westlake.edu.cn"  # 邮箱地址

  # Academic websites - 学术网站链接
  arxiv            : # arXiv个人资料链接 - 请更新为您的正确链接
  googlescholar    : "https://scholar.google.com/citations?hl=zh-CN&user=2G2-01QAAAAJ"  # Google Scholar链接
  impactstory      : # ImpactStory链接
  orcid            : #"https://orcid.org/0009-0004-6639-6359"  # ORCID链接
  semantic         : # Semantic Scholar链接
  pubmed           : # PubMed链接
  researchgate     : #"https://www.researchgate.net/profile/Luying-Feng-3?ev=hdr_xprf"  # ResearchGate链接
  yuque           :  "https://www.yuque.com/xiaobaigao-axvlp/" # 语雀用户名

  # Repositories and software development - 代码仓库和软件开发平台
  bitbucket        : # Bitbucket用户名 - 请更新为您的用户名
  codepen          : # CodePen用户名
  dribbble         : # Dribbble用户名
  github           : "https://github.com/EvomniDroid"  # GitHub链接
  kaggle           : # Kaggle用户名  
  stackoverflow    : # Stack Overflow用户ID或用户ID和姓名（例如："1"或"1/jeff-atwood"）

  # Social media - 社交媒体链接
  bluesky          : # Bluesky用户名 - 请替换为您的Bluesky用户名
  facebook         : # Facebook用户名
  flickr           : # Flickr用户名
  foursquare       : # Foursquare用户名
  goodreads        : # Goodreads用户名
  google_plus      : # Google+用户名
  keybase          : # Keybase用户名
  instagram        : # Instagram用户名
  lastfm           : # Last.fm用户名
  linkedin         : # LinkedIn用户名
  mastodon         : # Mastodon链接
  medium           : # Medium链接
  pinterest        : # Pinterest用户名
  soundcloud       : # SoundCloud用户名
  steam            : # Steam用户名
  telegram         : # Telegram链接
  tumblr           : # Tumblr用户名
  twitter          : # Twitter/X用户名
  vine             : # Vine用户名
  weibo            : # 微博用户名
  wikipedia        : # Wikipedia用户名
  xing             : # Xing用户名
  youtube          : # YouTube用户名
  zhihu            : # 知乎链接


# Site Settings - 网站设置
teaser                   :  # 默认预览图片文件名，放置在/images/目录下，例如 "500x300.png"
breadcrumbs              : false # 面包屑导航，true启用，false禁用（默认）
words_per_minute         : 160  # 每分钟阅读字数，用于计算阅读时间
future                   : true  # 是否显示未来日期的文章
read_more                : "disabled" # 如果启用，在摘要中添加"阅读更多"链接
talkmap_link             : false #设为true在演讲页面添加演讲地图链接
comments:  # 评论系统设置
  provider               : # 评论提供商: false（默认）, "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:  # Disqus评论设置
    shortname            :
  discourse:  # Discourse评论设置
    server               : # 例如: meta.discourse.org
  facebook:  # Facebook评论设置
    appid                :
    num_posts            : # 显示评论数量，默认5
    colorscheme          : # 颜色主题: "light"（默认）, "dark"
staticman:  # Staticman静态评论系统设置
  allowedFields          : ['name', 'email', 'url', 'message']  # 允许的字段
  branch                 : "gh-pages" # Git分支: "master", "gh-pages"
  commitMessage          : "New comment."  # 提交信息
  filename               : comment-{@timestamp}  # 文件名格式
  format                 : "yml"  # 文件格式
  moderation             : true  # 是否需要审核
  path                   : "_data/comments/{options.slug}"  # 存储路径
  requiredFields         : ['name', 'email', 'message']  # 必需字段
  transforms:  # 字段转换
    email                : "md5"  # 邮箱MD5加密
  generatedFields:  # 自动生成字段
    date:
      type               : "date"
      options:
        format           : "iso8601" # 日期格式: "iso8601"（默认）, "timestamp-seconds", "timestamp-milliseconds"
atom_feed:  # RSS订阅设置
  hide                   : false     # 设为true隐藏页脚中的RSS订阅
  path                   : # 留空（默认）使用feed.xml


# SEO Related - SEO相关设置
google_site_verification :  # Google站点验证码
bing_site_verification   :  # Bing站点验证码
alexa_site_verification  :  # Alexa站点验证码
yandex_site_verification :  # Yandex站点验证码


# Social Sharing - 社交分享设置
twitter:  # Twitter分享设置
  username               : &twitter
facebook:  # Facebook分享设置
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter默认站点图片
# For specifying social profiles - 指定社交档案
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # 类型: Person（个人）或Organization（组织），默认为Person
  name                   : # 如果用户或组织名称与站点名称不同
  links: # 社交媒体档案链接数组


# Analytics - 网站分析设置
analytics:
  provider               :  "false" # 分析提供商: false（默认）, "google", "google-universal", "google-analytics-4", "custom"
  google:  # Google Analytics设置
    tracking_id          :  # 跟踪ID


# Reading Files - 文件读取设置
include:  # 包含的文件和目录
  - .htaccess
  - _pages
  - files
exclude:  # 排除的文件和目录
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:  # 保留的文件（即使在--safe模式下）
  - .git
  - .svn
encoding: "utf-8"  # 文件编码
markdown_ext: "markdown,mkdown,mkdn,mkd,md"  # Markdown文件扩展名


# Conversion - 转换设置
markdown: kramdown  # Markdown处理器
highlighter: rouge  # 代码高亮器
lsi: false  # 潜在语义索引
excerpt_separator: "\n\n"  # 摘要分隔符
incremental: false  # 增量构建


# Markdown Processing - Markdown处理设置
kramdown:
  input: GFM  # 输入格式: GitHub Flavored Markdown
  hard_wrap: false  # 硬换行
  auto_ids: true  # 自动生成ID
  footnote_nr: 1  # 脚注起始编号
  entity_output: as_char  # 实体输出格式
  toc_levels: 1..6  # 目录层级
  smart_quotes: lsquo,rsquo,ldquo,rdquo  # 智能引号
  enable_coderay: false  # 启用CodeRay


# Collections - 集合设置
collections:
  teaching:  # 教学集合
    output: true  # 生成页面
    permalink: /:collection/:path/  # 永久链接格式
  publications:  # 出版物集合
    output: true
    permalink: /:collection/:path/
  portfolio:  # 作品集集合
    output: true
    permalink: /:collection/:path/
  talks:  # 演讲集合
    output: true
    permalink: /:collection/:path/


# Defaults - 默认设置
defaults:
  # _posts - 文章默认设置
  - scope:
      path: ""  # 路径
      type: posts  # 类型
    values:
      layout: single  # 布局
      author_profile: true  # 显示作者信息
      read_time: true  # 显示阅读时间
      comments: true  # 启用评论
      share: true  # 启用分享
      related: true  # 显示相关文章
  # _pages - 页面默认设置
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications - 出版物默认设置
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
# Sass/SCSS - 样式设置
sass:
  sass_dir: _sass  # Sass文件目录
  style: compressed # 输出样式: nested, expanded, compact, compressed


# Outputting - 输出设置
permalink: /:categories/:title/  # 永久链接格式
# paginate: 5 # 每页文章数量
# paginate_path: /page:num/  # 分页路径
timezone: America/Los_Angeles # 时区设置


# Plugins - 插件设置
plugins:
  - jekyll-paginate  # 分页插件
  - jekyll-sitemap  # 站点地图插件
  - jekyll-gist  # Gist插件
  - jekyll-feed  # RSS订阅插件
  - jekyll-redirect-from  # 重定向插件
# mimic GitHub Pages with --safe - 使用--safe模式模拟GitHub Pages
whitelist:  # 白名单插件
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives - 归档设置
#  Type - 类型
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples) - 路径示例
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:  # 分类归档
  type: liquid  # 类型: liquid或jekyll-archives
  path: /categories/  # 归档路径
tag_archive:  # 标签归档
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:  # Jekyll Archives插件设置
#   enabled:  # 启用的归档类型
#     - categories
#     - tags
#   layouts:  # 布局设置
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:  # 永久链接设置
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression - HTML压缩设置
# - http://jch.penibelst.de/
compress_html:
  clippings: all  # 压缩所有内容
  ignore:  # 忽略的环境
    envs: development  # 开发环境不压缩
